// Moneyland starter catalog (design engine v2). Every product is a big, themed bundle built from research:
// bundles of 20+ pages and sets of 3+ prints sell 3-5x better than single pages.
const ABC = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
const T13 = a => a.slice(0, 13);
const SEEDS = [
 { category: "kids", theme: "christmas", title: "Kids Christmas Activity Book", subtitle: "Mazes, I spy, word search, math, dot to dot, Santa letter and more",
   pages: [
    { template: "ispy", title: "Christmas I Spy", sheets: 2 },
    { template: "maze", count: 4, difficulty: 1 },
    { template: "wordsearch", title: "Christmas Word Search", words: ["santa", "reindeer", "sleigh", "snowman", "stocking", "candy", "cookies", "elf", "gifts", "star", "bells", "tree", "mittens", "snow"], level: 2 },
    { template: "scramble", title: "Christmas Word Scramble", words: ["santa", "jolly", "gift", "snow", "candle", "wreath", "angel", "cocoa", "carol", "merry"] },
    { template: "counting", title: "Count the Christmas Things", sheets: 2, max: 10, icons: ["tree", "star", "gift", "snowman", "candycane", "bell", "ornament", "stocking", "gingerbread", "mitten", "cookie", "snowflake"] },
    { template: "math", title: "Christmas Addition", op: "+", min: 0, max: 10, count: 20 },
    { template: "math", title: "Christmas Subtraction", op: "-", min: 0, max: 10, count: 20 },
    { template: "dotdot", count: 3, icons: ["tree", "star", "gingerbread", "stocking", "bell"] },
    { template: "matching", title: "Match the Christmas Pictures", icons: ["tree", "snowman", "gift", "bell", "stocking", "star"] },
    { template: "drawing", prompts: ["Draw your Christmas tree", "Draw what you want Santa to bring", "Draw a snowman family"] },
    { template: "letter", title: "My Letter to Santa", prompts: ["Dear Santa,", "My name is", "This year I was very good at", "For Christmas I would love", "I will leave you"], lines: 12 },
    { template: "countdown", title: "Christmas Countdown", days: 25, shape: "tree", prizeLabel: "Merry Christmas! Color one tree each night." },
    { template: "bingo", title: "Christmas Bingo", cards: 4, icons: ["tree", "star", "gift", "snowman", "candycane", "bell", "ornament", "stocking", "gingerbread", "mitten", "cookie", "snowflake", "moon", "heart", "house", "bow"] },
    { template: "certificate", title: "Official Nice List", kicker: "Certificate", subtitle: "Santa is proud to place", body: "on the Official Nice List for being kind, helpful and full of Christmas cheer this year.", signLabel: "Santa Claus" }],
   listing: { etsyTitle: "Kids Christmas Activity Book Printable, Christmas Worksheets, Mazes, I Spy, Word Search, Bingo, Santa Letter, Holiday Activities PDF",
     tags: T13(["christmas activity", "kids christmas", "christmas printable", "letter to santa", "christmas bingo", "christmas i spy", "christmas maze", "word search kids", "holiday activities", "christmas worksheet", "classroom christmas", "homeschool", "christmas games"]), price: 7.99,
     description: "A big Christmas activity book that keeps kids happy all December, from car rides to classroom parties. Print what you need, as many times as you like." } },

 { category: "planner", theme: "navy", title: "Christmas Planner and Gift Tracker", subtitle: "Budget, gifts, cards, menus and a December calendar in one binder",
   pages: [
    { template: "calendar", year: 2026, months: [11, 12], yearPage: false },
    { template: "table", title: "Holiday Budget", columns: ["Category", "Budget", "Spent", "Left"], rowLabels: ["Gifts", "Food", "Decorations", "Cards and postage", "Travel", "Parties", "Clothes", "Charity", "Other"], totalRow: true, rows: 12 },
    { template: "table", title: "Christmas Gift List", columns: ["Name", "Gift idea", "Budget", "Bought", "Wrapped"], rows: 22, fieldsList: ["Year"] },
    { template: "table", title: "Stocking Stuffers", columns: ["For", "Item", "Cost", "Done"], rows: 20 },
    { template: "table", title: "Christmas Card List", columns: ["Name", "Address", "Sent", "Received"], rows: 22 },
    { template: "planner", title: "Christmas Dinner Planner", fieldsList: ["Date", "Guests"], sections: [{ head: "Menu", kind: "lines", count: 8 }, { head: "Shopping list", kind: "checks", count: 8 }, { head: "Cooking timeline", kind: "hours", count: 10, wide: true }] },
    { template: "planner", title: "Holiday To Do List", sections: [{ head: "Decorate", kind: "checks", count: 8 }, { head: "Shop", kind: "checks", count: 8 }, { head: "Bake", kind: "checks", count: 8 }, { head: "Plan and book", kind: "checks", count: 8 }] },
    { template: "table", title: "Holiday Events", columns: ["Date", "Event", "Time", "Bring", "RSVP"], rows: 16 },
    { template: "table", title: "Baking Plan", columns: ["Recipe", "Day", "Ingredients needed", "Done"], rows: 14 },
    { template: "notes", title: "Christmas Notes", style: "lined" }],
   listing: { etsyTitle: "Christmas Planner Printable, Holiday Budget, Gift Tracker, Christmas Card List, Dinner Planner, December Calendar, Holiday Binder PDF",
     tags: T13(["christmas planner", "gift list", "holiday budget", "christmas budget", "gift tracker", "card list", "holiday planner", "meal planner", "christmas list", "printable planner", "holiday organizer", "christmas binder", "pdf planner"]), price: 6.99,
     description: "Plan the whole holiday season in one calm, organized binder: the budget, every gift, cards, events, baking and Christmas dinner." } },

 { category: "kids", theme: "christmas", title: "Christmas Countdown and Advent Activity Set", subtitle: "A 25 night countdown chart plus 25 easy advent activity ideas",
   pages: [
    { template: "countdown", title: "Christmas Countdown", days: 25, shape: "star", prizeLabel: "Color one star every night until Christmas!" },
    { template: "countdown", title: "Sleeps Until Christmas", days: 25, shape: "tree" },
    { template: "chart", title: "Advent Activities Week 1", rowHead: "Activity", rows: ["Write a letter to Santa", "Make a paper snowflake", "Read a Christmas story", "Bake cookies together", "Make a card for a friend", "Have a cocoa movie night", "Sing a Christmas song"], columns: ["Done"] },
    { template: "chart", title: "Advent Activities Week 2", rowHead: "Activity", rows: ["Decorate the tree", "Donate a toy", "Make a paper chain", "Look at Christmas lights", "Build a blanket fort", "Draw a winter picture", "Call a grandparent"], columns: ["Done"] },
    { template: "chart", title: "Advent Activities Week 3", rowHead: "Activity", rows: ["Wrap a present", "Make a gingerbread house", "Play a board game", "Write a thank you note", "Make an ornament", "Have a pajama day", "Leave a treat for a neighbor"], columns: ["Done"] },
    { template: "chart", title: "Advent Activities Week 4", rowHead: "Activity", rows: ["Watch a Christmas movie", "Make reindeer food", "Read The Night Before Christmas", "Set out cookies for Santa"], columns: ["Done"] }],
   listing: { etsyTitle: "Christmas Countdown Chart for Kids, Printable Advent Calendar Activities, 25 Days of Christmas, December Countdown PDF",
     tags: T13(["christmas countdown", "advent calendar", "kids countdown", "december countdown", "christmas printable", "25 days", "kids christmas", "advent activities", "advent printable", "countdown chart", "classroom", "toddler christmas", "pdf printable"]), price: 3.99,
     description: "Count down to Christmas with color-in charts and a full list of easy, low-cost family activities for every day of advent." } },

 { category: "kids", theme: "christmas", title: "Letter to Santa Kit", subtitle: "Santa letters, wish list, nice list certificate and a reindeer food tag",
   pages: [
    { template: "letter", title: "My Letter to Santa", prompts: ["Dear Santa,", "My name is", "I am      years old", "This year I was kind when", "For Christmas I wish for", "Love,"], lines: 12 },
    { template: "letter", title: "Dear Santa", prompts: ["Dear Santa,"], lines: 14 },
    { template: "table", title: "My Christmas Wish List", columns: ["I wish for", "Why I want it"], rows: 12, fieldsList: ["Name"] },
    { template: "drawing", prompts: ["Draw Santa and his sleigh", "Draw the best present ever"] },
    { template: "certificate", title: "Official Nice List", kicker: "Certificate", subtitle: "Santa is proud to place", body: "on the Official Nice List for being kind, helpful and full of Christmas cheer this year.", signLabel: "Santa Claus" },
    { template: "labels", title: "Reindeer Food and Cookie Tags", labels: ["Magic Reindeer Food", "Cookies for Santa", "Milk for Santa", "Carrots for the reindeer"], blankLine: false }],
   listing: { etsyTitle: "Letter to Santa Printable Kit, Christmas Wish List, Nice List Certificate, Santa Cookie Tags, Kids Christmas Eve Box PDF",
     tags: T13(["letter to santa", "nice list", "santa certificate", "christmas letter", "kids christmas", "dear santa", "christmas printable", "wish list kids", "north pole", "christmas eve box", "santa cookies", "kids activity", "pdf printable"]), price: 3.99,
     description: "Everything for the letter-to-Santa tradition: two letter styles, a wish list, drawing pages, an official nice list certificate and tags for the cookies." } },

 { category: "planner", theme: "sage_boho", title: "2027 Goal and Habit Planner", subtitle: "plan your best year",
   pages: [
    { template: "calendar", year: 2027 },
    { template: "goals", title: "My 2027 Goals", count: 3 },
    { template: "planner", title: "Year in Focus", sections: [{ head: "Word of the year", kind: "lines", count: 2, wide: true }, { head: "Health", kind: "bullets", count: 5 }, { head: "Money", kind: "bullets", count: 5 }, { head: "Home and family", kind: "bullets", count: 5 }, { head: "Growth", kind: "bullets", count: 5 }] },
    { template: "habit", habits: ["Drink 8 glasses of water", "Read 20 minutes", "Move 30 minutes", "Sleep by 11 pm", "No phone at meals", "Journal", "Take vitamins", "Save money"] },
    { template: "weekly" }, { template: "daily" },
    { template: "table", title: "Bucket List", columns: ["Dream", "Why", "Done"], rows: 20 },
    { template: "planner", title: "Monthly Review", fieldsList: ["Month"], sections: [{ head: "Wins", kind: "bullets", count: 5 }, { head: "Lessons", kind: "lines", count: 5 }, { head: "Next month focus", kind: "checks", count: 5, wide: true }, { head: "Notes", kind: "dots", count: 6, wide: true }] },
    { template: "notes", title: "Notes", style: "dots" }],
   listing: { etsyTitle: "2027 Planner Printable, Goal Planner, Habit Tracker, 2027 Calendar, Weekly and Daily Planner, Bucket List, Boho Planner PDF",
     tags: T13(["2027 planner", "goal planner", "2027 calendar", "goal setting", "habit tracker", "bucket list", "new year goals", "boho planner", "resolutions", "daily planner", "printable planner", "weekly planner", "pdf planner"]), price: 8.99,
     description: "A calm, beautiful 2027 planner: a full year of calendars plus goal setting, habit tracking, weekly and daily pages and monthly reviews." } },

 { category: "planner", theme: "minimal", title: "Budget Planner Bundle", subtitle: "Budget, bills, expenses, savings and debt payoff in one set",
   pages: [
    { template: "table", title: "Monthly Budget", columns: ["Category", "Planned", "Actual", "Difference"], rowLabels: ["Income", "Rent or mortgage", "Utilities", "Groceries", "Transport", "Phone and internet", "Insurance", "Childcare", "Debt payments", "Savings", "Eating out", "Fun", "Gifts", "Other"], totalRow: true, rows: 16, fieldsList: ["Month", "Year"] },
    { template: "table", title: "Bill Tracker", columns: ["Bill", "Due date", "Amount", "Paid", "Notes"], rows: 18, fieldsList: ["Month"] },
    { template: "table", title: "Expense Tracker", columns: ["Date", "Description", "Category", "Amount"], rows: 24, fieldsList: ["Month"] },
    { template: "table", title: "Savings Tracker", columns: ["Date", "Deposit", "Total saved", "Goal left"], rows: 20, fieldsList: ["Saving for", "Goal"] },
    { template: "table", title: "Debt Payoff Tracker", columns: ["Date", "Payment", "Balance left", "Notes"], rows: 20, fieldsList: ["Debt", "Starting balance"] },
    { template: "table", title: "Annual Expenses", columns: ["Expense", "Month due", "Amount", "Monthly set aside"], rows: 16 },
    { template: "table", title: "No Spend Challenge", columns: ["Day", "Spent nothing", "Notes"], rowLabels: Array.from({ length: 21 }, (_, i) => "Day " + (i + 1)), rows: 21 },
    { template: "planner", title: "Financial Goals", sections: [{ head: "This month", kind: "checks", count: 6 }, { head: "This year", kind: "checks", count: 6 }, { head: "Why it matters", kind: "lines", count: 6, wide: true }] }],
   listing: { etsyTitle: "Budget Planner Printable Bundle, Monthly Budget, Bill Tracker, Expense Tracker, Savings Tracker, Debt Payoff, Finance Binder PDF",
     tags: T13(["budget planner", "budget printable", "expense tracker", "bill tracker", "savings tracker", "debt payoff", "monthly budget", "finance planner", "money planner", "budget bundle", "budget binder", "no spend", "pdf planner"]), price: 6.99,
     description: "A clean, simple budget binder that makes money feel manageable: monthly budget, bills, spending, savings, debt payoff and a no-spend challenge." } },

 { category: "planner", theme: "terracotta", title: "Meal Planner Bundle", subtitle: "Weekly menus, grocery lists, recipes and a pantry inventory",
   pages: [
    { template: "meal", title: "Weekly Meal Planner" }, { template: "meal", title: "Weekly Meal Planner", meals: ["Breakfast", "Lunch", "Dinner"] },
    { template: "planner", title: "Grocery List", sections: [{ head: "Produce", kind: "checks", count: 10 }, { head: "Dairy and eggs", kind: "checks", count: 10 }, { head: "Meat and fish", kind: "checks", count: 8 }, { head: "Pantry", kind: "checks", count: 8 }, { head: "Frozen", kind: "checks", count: 6 }, { head: "Other", kind: "checks", count: 6 }] },
    { template: "planner", title: "Recipe Card", fieldsList: ["Recipe", "Serves", "Time"], sections: [{ head: "Ingredients", kind: "bullets", count: 10 }, { head: "Steps", kind: "lines", count: 10 }, { head: "Notes", kind: "lines", count: 4, wide: true }] },
    { template: "table", title: "Pantry Inventory", columns: ["Item", "Have", "Need", "Expires"], rows: 24 },
    { template: "table", title: "Family Favorite Meals", columns: ["Meal", "Who loves it", "Notes"], rows: 20 },
    { template: "table", title: "Freezer Inventory", columns: ["Item", "Date frozen", "Amount", "Use by"], rows: 20 }],
   listing: { etsyTitle: "Meal Planner Printable Bundle, Weekly Menu Planner, Grocery List, Recipe Card, Pantry and Freezer Inventory, Kitchen Binder PDF",
     tags: T13(["meal planner", "grocery list", "recipe card", "weekly menu", "meal plan", "food planner", "family planner", "kitchen printable", "pantry inventory", "menu planner", "meal prep", "freezer inventory", "pdf planner"]), price: 5.99,
     description: "Take the stress out of what's for dinner with weekly menus, a grocery list by aisle, recipe cards and pantry and freezer trackers." } },

 { category: "planner", theme: "blush", title: "Cleaning Schedule Bundle", subtitle: "Daily, weekly, monthly and seasonal cleaning checklists",
   pages: [
    { template: "chart", title: "Daily Cleaning Checklist", rowHead: "Task", rows: ["Make the beds", "Wash dishes", "Wipe kitchen counters", "Quick tidy living room", "Sweep the kitchen", "Laundry load", "Take out trash"] },
    { template: "chart", title: "Weekly Cleaning Schedule", rowHead: "Room", rows: ["Kitchen", "Bathrooms", "Bedrooms", "Living room", "Floors", "Laundry", "Dusting"] },
    { template: "table", title: "Monthly Deep Clean", columns: ["Task", "Week", "Done"], rowLabels: ["Clean the oven", "Clean the fridge", "Wash windows", "Dust ceiling fans", "Clean baseboards", "Wash shower curtain", "Vacuum couch", "Clean light switches", "Declutter a closet", "Wipe cabinets"], rows: 14 },
    { template: "planner", title: "Seasonal Cleaning", sections: [{ head: "Spring", kind: "checks", count: 8 }, { head: "Summer", kind: "checks", count: 8 }, { head: "Fall", kind: "checks", count: 8 }, { head: "Winter", kind: "checks", count: 8 }] },
    { template: "chart", title: "Kids Chores", rowHead: "Chore", rows: ["Make bed", "Pick up toys", "Feed the pet", "Set the table", "Put away laundry"] },
    { template: "table", title: "Cleaning Supplies List", columns: ["Supply", "Have", "Buy"], rows: 20 }],
   listing: { etsyTitle: "Cleaning Schedule Printable Bundle, Daily Cleaning Checklist, Weekly Chore Chart, Monthly Deep Clean, Seasonal Cleaning List PDF",
     tags: T13(["cleaning schedule", "cleaning checklist", "chore chart", "house cleaning", "cleaning planner", "weekly cleaning", "deep clean", "home organization", "household chores", "cleaning routine", "adhd cleaning", "printable checklist", "pdf planner"]), price: 4.99,
     description: "A simple system for a cleaner home: daily, weekly, monthly and seasonal checklists, plus kids chores and a supplies list." } },

 { category: "planner", theme: "sage_boho", title: "Habit and Wellness Tracker Pack", subtitle: "small steps, big changes",
   pages: [
    { template: "habit", title: "Habit Tracker" }, { template: "habit", title: "Self Care Tracker", habits: ["Morning stretch", "Drink water", "Eat a vegetable", "Go outside", "Read", "Gratitude", "Screen-free hour", "Early bedtime"] },
    { template: "table", title: "Water Tracker", columns: ["Day", "Glasses", "Notes"], rowLabels: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"], rows: 7 },
    { template: "table", title: "Sleep Log", columns: ["Date", "Bedtime", "Wake up", "Hours", "Quality"], rows: 20 },
    { template: "table", title: "Mood Journal", columns: ["Date", "Mood", "What helped", "Notes"], rows: 18 },
    { template: "table", title: "Workout Log", columns: ["Date", "Workout", "Time", "Notes"], rows: 20 },
    { template: "planner", title: "Weekly Reflection", fieldsList: ["Week of"], sections: [{ head: "What went well", kind: "bullets", count: 5 }, { head: "What was hard", kind: "bullets", count: 5 }, { head: "I am grateful for", kind: "lines", count: 5, wide: true }, { head: "Next week I will", kind: "checks", count: 5, wide: true }] }],
   listing: { etsyTitle: "Habit Tracker Printable, Wellness Planner, Water Tracker, Sleep Log, Mood Journal, Workout Log, Self Care Planner PDF",
     tags: T13(["habit tracker", "wellness planner", "water tracker", "sleep log", "mood tracker", "workout log", "self care", "health planner", "fitness tracker", "daily habits", "wellness printable", "journal pages", "pdf planner"]), price: 4.99,
     description: "Build better habits with gentle, beautiful trackers for habits, water, sleep, mood and workouts, plus a weekly reflection." } },

 { category: "kids", theme: "kids_bright", title: "Kindergarten Math Workbook", subtitle: "Counting, addition and subtraction practice with answer keys",
   pages: [
    { template: "counting", title: "Count and Circle", sheets: 3, max: 10 },
    { template: "tracing", mode: "numbers", numbers: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"] },
    { template: "math", title: "Adding to 5", op: "+", min: 0, max: 5, count: 20, sheets: 2 },
    { template: "math", title: "Adding to 10", op: "+", min: 0, max: 10, count: 20, sheets: 3 },
    { template: "math", title: "Taking Away within 5", op: "-", min: 0, max: 5, count: 20, sheets: 2 },
    { template: "math", title: "Taking Away within 10", op: "-", min: 0, max: 10, count: 20, sheets: 3 },
    { template: "ispy", title: "I Spy and Count", sheets: 2 },
    { template: "reward", title: "Math Star Chart", spots: 20, shape: "star" }],
   listing: { etsyTitle: "Kindergarten Math Worksheets Printable, Addition and Subtraction Practice, Counting Worksheets, Answer Keys, Homeschool Math PDF",
     tags: T13(["kindergarten math", "math worksheets", "addition worksheet", "subtraction", "homeschool math", "counting worksheet", "math practice", "answer key", "math facts", "kids worksheets", "preschool math", "first grade math", "pdf worksheets"]), price: 5.99,
     description: "A colorful kindergarten math workbook with counting, number tracing, addition and subtraction, I spy and full answer keys." } },

 { category: "kids", theme: "kids_pastel", title: "Alphabet and Number Tracing Workbook", subtitle: "Trace A to Z, numbers 1 to 20 and first sight words",
   pages: [
    { template: "tracing", letters: ABC },
    { template: "tracing", mode: "numbers", numbers: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"] },
    { template: "tracing", title: "Sight Words", words: ["the", "and", "you", "see", "can", "my", "we", "like", "is", "it", "go", "to"] },
    { template: "shapes" },
    { template: "reward", title: "Writing Star Chart", spots: 26, shape: "star" }],
   listing: { etsyTitle: "Alphabet Tracing Worksheets Printable, ABC Letter Tracing Book, Number Tracing 1-20, Sight Words, Preschool Handwriting PDF",
     tags: T13(["letter tracing", "handwriting practice", "tracing worksheets", "abc tracing", "number tracing", "sight words", "preschool printable", "kindergarten", "homeschool", "alphabet practice", "writing practice", "learn to write", "pdf worksheets"]), price: 5.99,
     description: "A full handwriting workbook: one page for every letter with a picture to match, numbers 1 to 20, sight words and shape tracing." } },

 { category: "kids", theme: "kids_bright", title: "Chore Chart Bundle by Age", subtitle: "Age-right chores and routines for ages 3 to 12",
   pages: [
    { template: "chart", title: "Little Helper Chores", subtitle: "Ages 3 to 5", rowHead: "Chore", rows: ["Pick up toys", "Put clothes in hamper", "Feed the pet", "Help set the table", "Wipe up spills"] },
    { template: "chart", title: "Chores for Ages 6 to 8", rowHead: "Chore", rows: ["Make my bed", "Clear my plate", "Put away laundry", "Water plants", "Tidy my room", "Help with groceries"] },
    { template: "chart", title: "Chores for Ages 9 to 12", rowHead: "Chore", rows: ["Load the dishwasher", "Vacuum a room", "Take out trash", "Fold laundry", "Pack my lunch", "Clean the bathroom sink"] },
    { template: "chart", title: "Morning Routine", rowHead: "Step", rows: ["Get dressed", "Brush teeth", "Eat breakfast", "Brush hair", "Pack my bag"] },
    { template: "chart", title: "Bedtime Routine", rowHead: "Step", rows: ["Bath time", "Pajamas on", "Brush teeth", "Read a story", "Lights out"] },
    { template: "reward", title: "Chore Reward Chart", spots: 20, shape: "heart" }],
   listing: { etsyTitle: "Chore Chart for Kids Printable, Chore Chart by Age 3-5, 6-8, 9-12, Morning and Bedtime Routine Chart, Responsibility Chart PDF",
     tags: T13(["chore chart", "kids chores", "chore chart kids", "responsibility chart", "chores by age", "toddler chores", "routine chart", "family chores", "kids printable", "bedtime routine", "morning routine", "parenting", "pdf printable"]), price: 4.99,
     description: "Age-right chore charts for little helpers to tweens, plus morning and bedtime routines and a reward chart to keep it fun." } },

 { category: "kids", theme: "kids_pastel", title: "Reward and Behavior Chart Bundle", subtitle: "Sticker charts for stars, potty training, reading and good days",
   pages: [
    { template: "reward", title: "My 10 Star Chart", spots: 10, shape: "star" }, { template: "reward", title: "My 20 Star Chart", spots: 20, shape: "star" },
    { template: "reward", title: "My 30 Star Chart", spots: 30, shape: "star" }, { template: "reward", title: "Potty Training Chart", spots: 20, shape: "heart" },
    { template: "reward", title: "Reading Reward Chart", spots: 25, shape: "book" }, { template: "reward", title: "Good Listening Chart", spots: 15, shape: "balloon" },
    { template: "reward", title: "Kindness Chart", spots: 20, shape: "heart" },
    { template: "chart", title: "Weekly Behavior Chart", rowHead: "Goal", rows: ["Use kind words", "Listen the first time", "Share and take turns", "Clean up after myself", "Try my best"] },
    { template: "certificate", title: "Super Star Award", kicker: "Certificate", subtitle: "This award is proudly given to", body: "for working hard, being kind and filling up the star chart!", signLabel: "Signed" }],
   listing: { etsyTitle: "Reward Chart Printable Bundle, Sticker Chart for Kids, Behavior Chart, Potty Training Chart, Reading Chart, Star Chart PDF",
     tags: T13(["reward chart", "sticker chart", "behavior chart", "potty training", "reading chart", "kids printable", "incentive chart", "toddler chart", "classroom reward", "positive behavior", "parenting tool", "star chart", "pdf printable"]), price: 4.99,
     description: "Cheerful reward charts for every goal: stars, potty training, reading, listening and kindness, plus a weekly behavior chart and an award." } },

 { category: "party", theme: "party_bright", title: "Kids Birthday Party Pack", subtitle: "Signs, games, food labels, toppers, banner and bingo",
   pages: [
    { template: "sign", title: "Welcome to the Party", kicker: "hooray" }, { template: "sign", title: "Happy Birthday", subtitle: "Let's celebrate!" },
    { template: "banner", text: "HAPPY BIRTHDAY" },
    { template: "toppers", text: "Happy Birthday" },
    { template: "labels", title: "Food Labels", labels: ["Pizza", "Cupcakes", "Fruit", "Juice", "Chips", "Cookies", "Popcorn", "Water"] },
    { template: "labels", title: "Favor Tags", labels: ["Thanks for coming!", "Thanks for coming!", "Thanks for coming!", "Thanks for coming!", "Thanks for coming!", "Thanks for coming!"] },
    { template: "bingo", title: "Birthday Bingo", cards: 8, icons: ["balloon", "cupcake", "gift", "star", "crown", "bow", "heart", "sun", "rainbow", "ball", "cookie", "bear", "bunny", "rocket"] },
    { template: "game", title: "Would You Rather", questions: ["Eat cake or ice cream", "Be a dog or a cat", "Fly or be invisible", "Live in a castle or a treehouse", "Swim with dolphins or ride a horse", "Eat pizza or tacos", "Play in snow or at the beach", "Be a pirate or an astronaut"] },
    { template: "invitation", title: "Birthday Party" }],
   listing: { etsyTitle: "Kids Birthday Party Printable Pack, Happy Birthday Banner, Welcome Sign, Cupcake Toppers, Food Labels, Birthday Bingo, Party Games PDF",
     tags: T13(["birthday party", "party printable", "birthday banner", "food labels", "cupcake toppers", "birthday bingo", "kids birthday", "party decor", "birthday sign", "party games", "girl birthday", "boy birthday", "pdf printable"]), price: 6.99,
     description: "Throw a bright, happy party in minutes: signs, a full banner, toppers, labels, tags, picture bingo, a game and an invitation." } },

 { category: "party", theme: "baby_soft", title: "Baby Shower Game Bundle", subtitle: "Bingo, word games, predictions and advice cards",
   pages: [
    { template: "sign", title: "Welcome Baby", kicker: "oh baby" },
    { template: "bingo", title: "Baby Shower Bingo", cards: 10, words: ["bottle", "diaper", "onesie", "rattle", "crib", "blanket", "bib", "stroller", "pacifier", "teddy bear", "lotion", "socks", "booties", "wipes", "car seat", "high chair", "bath toys", "books", "monitor", "swaddle", "night light", "mobile", "burp cloth", "hat", "mittens", "carrier", "toys", "shampoo"] },
    { template: "scramble", title: "Baby Word Scramble", words: ["bottle", "diaper", "cradle", "rattle", "stroller", "blanket", "lullaby", "nursery", "pacifier", "bonnet"] },
    { template: "wordsearch", title: "Baby Word Search", words: ["baby", "bottle", "diaper", "crib", "rattle", "onesie", "bib", "stroller", "blanket", "lullaby", "nursery", "teddy"], level: 2 },
    { template: "table", title: "Baby Predictions", columns: ["Guest", "Birth date", "Weight", "Hair color", "Looks like"], rows: 18 },
    { template: "game", title: "Mommy or Daddy", questions: ["Who is the better cook", "Who will change more diapers", "Who will cry at the first day of school", "Who is more likely to sing lullabies", "Who will be the stricter parent", "Who is the bigger kid at heart", "Who will take the most photos", "Who will fall asleep first"] },
    { template: "labels", title: "Advice for the Parents", labels: ["My advice for Mom", "My advice for Dad", "Wishes for Baby", "Best parenting tip"], blankLine: true }],
   listing: { etsyTitle: "Baby Shower Games Printable Bundle, Baby Shower Bingo, Word Scramble, Word Search, Baby Predictions, Advice Cards, Gender Neutral PDF",
     tags: T13(["baby shower games", "baby shower", "baby bingo", "word scramble", "baby predictions", "advice cards", "shower games", "gender neutral", "baby shower bingo", "party games", "shower printable", "word search", "pdf printable"]), price: 5.99,
     description: "Soft, gender-neutral baby shower games for every guest: bingo, puzzles, predictions, a parents game and advice cards." } },

 { category: "wallart", palette: "boho", title: "Boho Sun and Arch Wall Art Set of 3", subtitle: "Mid-century boho prints in warm terracotta",
   prints: [{ style: "arches", seed: "boho1" }, { style: "sun", seed: "boho2" }, { style: "botanical", seed: "boho3" }],
   listing: { etsyTitle: "Boho Wall Art Set of 3 Printable, Terracotta Arch Print, Sun Print, Botanical Print, Mid Century Boho Decor, Digital Download",
     tags: T13(["boho wall art", "set of 3 prints", "printable wall art", "terracotta art", "boho print", "rainbow arch", "sun print", "mid century art", "boho decor", "neutral wall art", "gallery wall", "living room art", "digital download"]), price: 7.99,
     description: "A warm, earthy set of three boho prints to bring a calm, modern feel to any room. Print at home or at any print shop." } },
 { category: "wallart", palette: "sage", title: "Sage Green Botanical Wall Art Set of 3", subtitle: "Calm sage and cream minimalist prints",
   prints: [{ style: "botanical", seed: "sage1" }, { style: "mountains", seed: "sage2" }, { style: "quote", seed: "sage3", text: "Grow through what you go through", font: "serif" }],
   listing: { etsyTitle: "Sage Green Wall Art Set of 3 Printable, Botanical Print, Mountain Print, Quote Print, Minimalist Neutral Decor, Digital Download",
     tags: T13(["sage green decor", "botanical print", "set of 3 prints", "printable wall art", "minimalist art", "mountain print", "quote print", "neutral wall art", "green wall art", "bedroom art", "gallery wall", "boho decor", "digital download"]), price: 7.99,
     description: "Soft sage greens and creams in three calming prints: a botanical stem, misty mountains and a gentle quote." } },
 { category: "wallart", palette: "blush", title: "Nursery Animal Wall Art Set of 3", subtitle: "Sweet animal prints for a baby room",
   prints: [{ style: "nursery", seed: "n1", icon: "bear", text: "Dream big little one", font: "serif" }, { style: "nursery", seed: "n2", icon: "bunny", text: "You are loved", font: "serif" }, { style: "nursery", seed: "n3", icon: "owl", text: "Hello little one", font: "serif" }],
   listing: { etsyTitle: "Nursery Wall Art Set of 3 Printable, Baby Animal Prints, Bear Bunny Owl, Neutral Nursery Decor, Kids Room Art, Digital Download",
     tags: T13(["nursery wall art", "nursery prints", "baby animal art", "set of 3 prints", "nursery decor", "kids room art", "printable nursery", "neutral nursery", "baby room decor", "bear print", "bunny print", "baby shower gift", "digital download"]), price: 6.99,
     description: "Three sweet animal prints with gentle sayings for a baby room or playroom." } },
];
SEEDS.forEach(s => { s.v = 2; if (s.category !== "wallart") s.template = "bundle"; });
module.exports = { SEEDS };
