// The page templates Moneyland's PDF maker understands. Shared by the product builder.
const TEMPLATES = `Page templates (exact JSON shapes; every page may also set "accent"):
chart (routine, chore, habit, cleaning grids): {"template":"chart","title":"max 40 chars","subtitle":"max 70 chars","rowHead":"Task|Habit|Chore|Room","rows":["max 30 chars"] (5-10),"columns":["Mon","Tue","Wed","Thu","Fri","Sat","Sun"] or other short labels (max 8),"footer":"max 60 chars or empty","fields":"e.g. Name: ______   Week of: ______"}
reward (sticker, behavior or countdown charts): {"template":"reward","title":"max 36 chars","subtitle":"max 60 chars","spots":10|15|20|25|30,"goal":"max 60 chars or a blank line of underscores","prizeLabel":"max 45 chars"}
math (problems and answer key are generated by code): {"template":"math","title":"max 40 chars","subtitle":"max 60 chars","op":"+"|"-"|"x","min":number,"max":number,"count":12|16|20|24|25|30}
tracing (handwriting): {"template":"tracing","title":"max 40 chars","subtitle":"max 60 chars","words":["letters or words, max 8 chars"] (4-6)}
table (trackers and logs): {"template":"table","title":"max 40 chars","subtitle":"max 80 chars","fields":"max 90 chars with ______ blanks","columns":["max 18 chars"] (3-6),"rows":8-22,"rowLabels":["optional labels prefilled in the first column"],"totalRow":true|false,"notes":["max 100 chars"] (0-2)}
planner (pages of boxes): {"template":"planner","title":"max 40 chars","subtitle":"max 70 chars","fields":"e.g. Date: ______","startHour":5-9,"sections":[{"head":"max 22 chars","kind":"lines"|"checks"|"hours","count":2-14,"wide":true|false}] (3-7)}
letter (lined letter with prompts): {"template":"letter","title":"max 36 chars","subtitle":"max 60 chars","prompts":["sentence starters, max 60 chars"] (2-6),"lines":6-16}
certificate: {"template":"certificate","title":"max 36 chars","subtitle":"max 50 chars","body":"max 120 chars","signLabel":"max 30 chars"}
bingo (one 5x5 card; code shuffles words): {"template":"bingo","title":"max 30 chars","subtitle":"max 60 chars","words":[at least 24 short words, max 12 chars each]}
scramble (code scrambles words and makes the answer key): {"template":"scramble","title":"max 36 chars","subtitle":"max 60 chars","words":["single words, 4-10 letters"] (8-15)}
labels (cut-out cards: food labels, favor tags, place cards): {"template":"labels","title":"max 36 chars","subtitle":"max 60 chars","labels":["text on each card, max 30 chars"] (4-8),"blankLine":true|false}
sign (party and event signs): {"template":"sign","title":"2-5 words","subtitle":"max 40 chars, ______ blanks allowed","lines":["max 50 chars"] (1-3)}
bundle (several pages sold together; a cover page is added by code): {"template":"bundle","title":"max 44 chars","subtitle":"max 80 chars","pages":[page objects from the list above] (2-10)}
Every product (single page or bundle) has: "category": "kids"|"planner"|"party", "accent": one of "purple","teal","orange","pink","blue","green","yellow","red","navy","sage", and "listing": {"etsyTitle":"keyword-rich Etsy title, max 140 chars","tags":[exactly 13 tags, each max 20 chars],"price": number between 2 and 12}.
Rules: plain friendly words; no brand names, characters, celebrities or trademarks; facts must be correct; bundles usually sell better than single pages.`;
module.exports = { TEMPLATES };
