// Autopilot: runs every hour. Builds products from the best research ideas, has the AI check each one,
// and publishes the ones that pass to Etsy, within a daily limit. Everything it does is written to the log.
const { cfg, db, claudeJSON } = require("./_lib");
const { etsyConfigured, link, publishProduct } = require("./_etsy");
const { buildProducts } = require("./_produce");

async function note(kind, text) { try { await db("autopilot_log", { method: "POST", prefer: "return=minimal", body: [{ kind, text: String(text).slice(0, 500) }] }); } catch (e) {} }

// A second AI pass reads the whole product before it goes live.
function stripArt(spec) { return JSON.parse(JSON.stringify(spec, (k, v) => k === "art" ? "(illustration)" : v)); }
async function qaCheck(spec) {
  const R = require("./_render"), content = [];
  try {
    const n = R.previewList(spec).length, picks = [0, 1, Math.floor(n / 2), n - 1].filter((v, i, a) => v >= 0 && v < n && a.indexOf(v) === i);
    picks.forEach(i => content.push({ type: "image", source: { type: "base64", media_type: "image/png", data: R.previewPNG(spec, i, 700).toString("base64") } }));
    content.push({ type: "image", source: { type: "base64", media_type: "image/png", data: R.photoPNG(spec, 0, 900).toString("base64") } });
  } catch (e) { return { pass: false, problems: "Could not render the product: " + e.message }; }
  const prompt = "You are the quality checker for a printable digital product about to be published on Etsy with no human review. The images above are some of its pages and its main listing photo. Check it carefully.\n"
    + "Fail it if ANY of these are true: the title, tags or description mention a picture, object or page that you cannot see in the images (for example trees, animals or a bow that are not there); text that overlaps, is cut off or runs outside its box; pages that look broken, empty or unprofessional; spelling or grammar mistakes; wrong facts; content that is not suitable for its buyers (kids products must be kid-safe); brand names, characters, celebrities, song lyrics, movie or TV show names or other trademarks (including in the Etsy title and tags); the title or tags promise something the pages do not contain; empty or nonsense pages; claims of certification or professional advice. Math problems and answer keys are generated by code, so do not check arithmetic.\n"
    + "Product JSON:\n" + JSON.stringify(stripArt(spec)).slice(0, 30000) + "\n\nReply with only JSON: {\"pass\": true|false, \"problems\": \"short list of problems, empty if none\"}";
  content.push({ type: "text", text: prompt });
  const r = (await claudeJSON({ tier: "smart", prompt: content, maxTokens: 800 })).data;
  return { pass: r.pass === true, problems: String(r.problems || "").slice(0, 400) };
}

module.exports = async (req, res) => {
  if (!/vercel-cron/i.test(String(req.headers["user-agent"] || ""))) return res.status(401).json({ error: "Not allowed." });
  const c = cfg(); const done = [];
  try {
    if (!c.db || !c.ai) return res.status(200).json({ skipped: "keys not set" });
    const settings = (await db("settings?id=eq.1"))[0] || { autopilot: true, max_listings_per_day: 5 };
    if (!settings.autopilot) return res.status(200).json({ skipped: "autopilot is off" });
    const started = Date.now(), timeLeft = () => 285000 - (Date.now() - started);

    // 0. Make sure the starter catalog is loaded (design engine v2).
    const starters = await db("products?select=id&source=eq.starter&limit=1");
    if (!starters.length) {
      const { SEEDS } = require("../lib/seeds"), B = require("../lib/design/book");
      const rows = SEEDS.slice().reverse().map(s0 => { const s = JSON.parse(JSON.stringify(s0)); try { s.pageCount = s.category === "wallart" ? s.prints.length : B.build(s).pages.length; } catch (e) {} return { status: "review", spec: s, price: Number(s.listing.price) || 5, source: "starter", design_version: 2 }; });
      await db("products", { method: "POST", prefer: "return=minimal", body: rows });
      await note("built", "Loaded the " + rows.length + " starter products in the new design.");
    }

    // 1. Publish: products waiting for approval, checked by AI, up to the daily limit.
    const etsyReady = etsyConfigured() && !!((await link()) || {}).refresh_token;
    if (settings.publish_on === false) done.push("publishing switched off");
    else if (etsyReady) {
      const since = new Date(Date.now() - 24 * 3600000).toISOString();
      const today = await db("products?select=id&auto_published=eq.true&published_at=gte." + since);
      let room = Math.max(0, (settings.max_listings_per_day || 5) - today.length);
      const queue = await db("products?select=*&status=in.(review,approved)&qa_note=is.null&order=id.desc&limit=6");
      for (const p of queue) {
        if (room <= 0 || timeLeft() < 60000) break;
        const qa = await qaCheck(p.spec);
        if (!qa.pass) {
          await db("products?id=eq." + p.id, { method: "PATCH", body: { qa_note: "Held back by the quality check: " + (qa.problems || "problems found") } });
          await note("held", "Held back \"" + p.spec.title + "\" for you to look at: " + qa.problems); done.push("held " + p.id); continue;
        }
        try {
          await publishProduct(p, { activate: true, auto: true });
          await db("products?id=eq." + p.id, { method: "PATCH", body: { qa_note: "Passed the quality check" } });
          await note("published", "Published on Etsy: \"" + p.spec.title + "\" at $" + p.price); done.push("published " + p.id); room--;
        } catch (e) {
          await db("products?id=eq." + p.id, { method: "PATCH", body: { qa_note: "Etsy upload failed: " + String(e.message || e).slice(0, 200) } });
          await note("error", "Could not publish \"" + p.spec.title + "\": " + (e.message || e)); done.push("error " + p.id);
        }
      }
    } else done.push("etsy not connected");

    // 2. Build: keep the line full from the best research ideas.
    const waiting = await db("products?select=id&status=in.(review,approved)&qa_note=is.null&source=neq.starter");
    if (settings.build_on !== false && waiting.length < 4 && timeLeft() > 200000) {
      const idea = (await db("ideas?select=*&status=eq.new&fits=eq.true&score=gte.8&order=score.desc,id.desc&limit=1"))[0];
      if (idea) {
        try { const made = await buildProducts({ ideaId: idea.id, deadline: started + 285000 }); await note("built", "Built \"" + (made[0] && made[0].spec.title) + "\" from research idea \"" + idea.title + "\""); done.push("built idea " + idea.id); }
        catch (e) { await note("error", "Could not build \"" + idea.title + "\": " + (e.message || e)); }
      }
    }
    return res.status(200).json({ ok: true, done });
  } catch (e) {
    await note("error", "Autopilot stopped: " + (e.message || e));
    return res.status(500).json({ error: String(e.message || e), done });
  }
};
