// Autopilot: runs every 10 minutes. Builds products from the best research ideas, has the AI check each one,
// and publishes the ones that pass to Etsy, within a daily limit. Everything it does is written to the log.
const { cfg, db, claudeJSON, beat } = require("./_lib");
const { etsyConfigured, link, publishProduct } = require("./_etsy");
const { buildProducts } = require("./_produce");

async function note(kind, text) { try { await db("autopilot_log", { method: "POST", prefer: "return=minimal", body: [{ kind, text: String(text).slice(0, 500) }] }); } catch (e) {} }

// A second AI pass reads the whole product before it goes live.
function stripArt(spec) { return JSON.parse(JSON.stringify(spec, (k, v) => k === "art" ? "(illustration)" : v)); }
// ChatGPT gives a second opinion first; Claude reads it, checks it against the pictures and makes the final call.
async function gptNotes(pngs, spec) {
  const O = require("./_openai");
  if (!O.configured()) return null;
  try {
    const out = await O.chatJSON(pngs.map(png => ({ type: "image", png })).concat([{ type: "text", text: "These are pages and the main listing photo of a printable product about to go on Etsy. Title: " + spec.title + ". Etsy title: " + ((spec.listing || {}).etsyTitle || "") + ". Tags: " + ((spec.listing || {}).tags || []).join(", ")
      + ". List every real problem you can see: overlapping or cut-off text, spelling mistakes, broken or empty pages, anything the title or tags promise that is not in the pictures, trademarks or characters, anything not kid-safe. Do not check math answers. Reply as JSON: {\"problems\": [\"short problem\", ...]} with an empty list if it looks good." }]), { maxTokens: 1500 });
    return (out.problems || []).map(String).slice(0, 12);
  } catch (e) { return null; }
}
async function qaCheck(spec) {
  const R = require("./_render"), content = [], pngs = [];
  try {
    const n = R.previewList(spec).length, picks = [0, 1, Math.floor(n / 2), n - 1].filter((v, i, a) => v >= 0 && v < n && a.indexOf(v) === i);
    picks.forEach(i => pngs.push(R.previewPNG(spec, i, 700)));
    pngs.push(R.photoPNG(spec, 0, 900));
    pngs.forEach(png => content.push({ type: "image", source: { type: "base64", media_type: "image/png", data: png.toString("base64") } }));
  } catch (e) { return { pass: false, problems: "Could not render the product: " + e.message }; }
  const notes = await gptNotes(pngs, spec);
  const prompt = "You are the quality checker for a printable digital product about to be published on Etsy with no human review. The images above are some of its pages and its main listing photo. Check it carefully.\n"
    + "Fail it if ANY of these are true: the title, tags or description mention a picture, object or page that you cannot see in the images (for example trees, animals or a bow that are not there); text that overlaps, is cut off or runs outside its box; pages that look broken, empty or unprofessional; spelling or grammar mistakes; wrong facts; content that is not suitable for its buyers (kids products must be kid-safe); brand names, characters, celebrities, song lyrics, movie or TV show names or other trademarks (including in the Etsy title and tags); the title or tags promise something the pages do not contain; empty or nonsense pages; claims of certification or professional advice. Math problems and answer keys are generated by code, so do not check arithmetic.\n"
    + (notes && notes.length ? "A second reviewer (ChatGPT) flagged these possible problems. Check each one yourself against the images and count only the ones that are really there: " + notes.join("; ") + "\n" : "")
    + "Product JSON:\n" + JSON.stringify(stripArt(spec)).slice(0, 30000) + "\n\nReply with only JSON and nothing else: {\"pass\": true|false, \"problems\": \"short list of problems, empty if none\"}";
  content.push({ type: "text", text: prompt });
  let r;
  try { r = (await claudeJSON({ tier: "smart", prompt: content, maxTokens: 1200 })).data; }
  catch (e) { return { pass: null, problems: "check did not finish: " + e.message }; }
  return { pass: r.pass === true, problems: String(r.problems || "").slice(0, 400) };
}

// Title contest: ChatGPT writes a rival Etsy title and tags, Claude picks the winner. The runner-up is kept for search tuning later.
async function titleContest(p) {
  const O = require("./_openai"), L = p.spec.listing || {};
  if (!O.configured() || L.contest) return;
  try {
    const rival = await O.chatJSON("Write the best possible Etsy title and 13 tags for this printable digital download so buyers find it in Etsy search.\nProduct: " + p.spec.title + " - " + (p.spec.subtitle || "") + "\nWhat is inside: " + ((p.spec.pages || []).map(pg => pg.title || pg.template).slice(0, 30).join(", ") || ((p.spec.prints || []).length + " art prints")) + "\nCurrent title: " + L.etsyTitle + "\nRules: title max 140 characters, main search phrase in the first 50 characters, natural wording, only describe what is really inside; 13 tags, each max 20 characters, real buyer search phrases, no repeats; no trademarks or brand names. JSON: {\"title\": \"...\", \"tags\": [13 strings]}", { maxTokens: 800 });
    const rt = String(rival.title || "").slice(0, 140), rtags = (rival.tags || []).map(t => String(t).replace(/[^A-Za-z0-9 \-']/g, "").slice(0, 20).trim()).filter(Boolean).slice(0, 13);
    if (rt.length < 20 || rtags.length < 8) return;
    const judge = (await claudeJSON({ tier: "smart", maxTokens: 600, prompt: "You run an Etsy shop. Pick the title and tags that will get more buyers to find and click this printable product in Etsy search, while being 100 percent accurate to what is inside (" + p.spec.title + ").\nA: " + L.etsyTitle + " | tags: " + (L.tags || []).join(", ") + "\nB: " + rt + " | tags: " + rtags.join(", ") + "\nReject any option that promises something not in the product or uses trademarks. Reply with only JSON: {\"winner\": \"A\" or \"B\", \"why\": \"one short sentence\"}" })).data;
    const useB = String(judge.winner).toUpperCase() === "B";
    const spec = Object.assign({}, p.spec, { listing: Object.assign({}, L, useB ? { etsyTitle: rt, tags: rtags, altTitle: L.etsyTitle, altTags: L.tags } : { altTitle: rt, altTags: rtags },
      { contest: { winner: useB ? "chatgpt" : "claude", why: String(judge.why || "").slice(0, 200), at: new Date().toISOString() } }) });
    await db("products?id=eq." + p.id, { method: "PATCH", body: { spec } });
    p.spec = spec;
    await note("contest", "Title contest for \"" + p.spec.title + "\": Claude picked " + (useB ? "ChatGPT's" : "its own") + " title. " + String(judge.why || "").slice(0, 160));
  } catch (e) { await note("contest", "Title contest skipped for \"" + p.spec.title + "\": " + String(e.message).slice(0, 160)); }
}

module.exports = async (req, res) => {
  if (!/vercel-cron/i.test(String(req.headers["user-agent"] || ""))) return res.status(401).json({ error: "Not allowed." });
  const c = cfg(); const done = [];
  try {
    if (!c.db || !c.ai) return res.status(200).json({ skipped: "keys not set" });
    const settings = (await db("settings?id=eq.1"))[0] || { autopilot: true, max_listings_per_day: 5 };
    if (!settings.autopilot) { await beat("autopilot", true, "switched off"); return res.status(200).json({ skipped: "autopilot is off" }); }
    const started = Date.now(), timeLeft = () => 285000 - (Date.now() - started);

    // 0. Make sure the starter catalog is loaded (design engine v2).
    const starters = await db("products?select=id&source=eq.starter&limit=1");
    if (!starters.length) {
      const { SEEDS } = require("../lib/seeds"), B = require("../lib/design/book");
      const rows = SEEDS.slice().reverse().map(s0 => { const s = JSON.parse(JSON.stringify(s0)); try { s.pageCount = s.category === "wallart" ? s.prints.length : B.build(s).pages.length; } catch (e) {} return { status: "review", spec: s, price: Number(s.listing.price) || 5, source: "starter", design_version: 2 }; });
      await db("products", { method: "POST", prefer: "return=minimal", body: rows });
      await note("built", "Loaded the " + rows.length + " starter products in the new design.");
    }

    // 1. Publish: products waiting for approval, checked by AI, up to the daily limit.
    const etsyReady = etsyConfigured() && !!((await link()) || {}).refresh_token;
    if (settings.publish_on === false) done.push("publishing switched off");
    else if (etsyReady) {
      const since = new Date(Date.now() - 24 * 3600000).toISOString();
      const today = await db("products?select=id&auto_published=eq.true&published_at=gte." + since);
      let room = Math.max(0, (settings.max_listings_per_day || 5) - today.length);
      const queue = await db("products?select=*&status=in.(review,approved)&qa_note=is.null&order=id.desc&limit=6");
      for (const p of queue) {
        if (room <= 0 || timeLeft() < 60000) break;
        const qa = await qaCheck(p.spec);
        if (qa.pass === null) { await note("error", "Quality check did not finish for \"" + p.spec.title + "\", will try again next hour."); continue; }
        if (!qa.pass) {
          await db("products?id=eq." + p.id, { method: "PATCH", body: { qa_note: "Held back by the quality check: " + (qa.problems || "problems found") } });
          await note("held", "Held back \"" + p.spec.title + "\" for you to look at: " + qa.problems); done.push("held " + p.id); continue;
        }
        try {
          await titleContest(p);
          await publishProduct(p, { activate: true, auto: true });
          await db("products?id=eq." + p.id, { method: "PATCH", body: { qa_note: "Passed the quality check" } });
          await note("published", "Published on Etsy: \"" + p.spec.title + "\" at $" + p.price); done.push("published " + p.id); room--;
        } catch (e) {
          await db("products?id=eq." + p.id, { method: "PATCH", body: { qa_note: "Etsy upload failed: " + String(e.message || e).slice(0, 200) } });
          await note("error", "Could not publish \"" + p.spec.title + "\": " + (e.message || e)); done.push("error " + p.id);
        }
      }
    } else done.push("etsy not connected");

    // 2. Build: keep the line full from the best research ideas.
    const waiting = await db("products?select=id&status=in.(review,approved)&qa_note=is.null&source=neq.starter");
    if (settings.build_on !== false && waiting.length < 4 && timeLeft() > 200000) {
      const idea = (await db("ideas?select=*&status=eq.new&fits=eq.true&score=gte.8&build_fails=lt.2&order=score.desc,id.desc&limit=1"))[0];
      if (idea) {
        try { const made = await buildProducts({ ideaId: idea.id, deadline: started + 285000 }); await note("built", "Built \"" + (made[0] && made[0].spec.title) + "\" from research idea \"" + idea.title + "\""); done.push("built idea " + idea.id); }
        catch (e) {
          const fails = (idea.build_fails || 0) + 1;
          await db("ideas?id=eq." + idea.id, { method: "PATCH", body: { build_fails: fails } }).catch(() => {});
          await note("error", "Could not build \"" + idea.title + "\": " + (e.message || e) + (fails >= 2 ? " Gave up on this idea after 2 tries; moving to the next one." : " Will try once more."));
        }
      }
    }
    await beat("autopilot", true, done.join(", "));
    return res.status(200).json({ ok: true, done });
  } catch (e) {
    await note("error", "Autopilot stopped: " + (e.message || e));
    await beat("autopilot", false, e.message || e);
    return res.status(500).json({ error: String(e.message || e), done });
  }
};
